[tool.poetry]
name = "python-twitter"
version = "0.1.0"
description = ""
authors = ["Fl√°vio Sotto"]
license = "none"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
